import dynamic from "next/dynamic";
import "./globals.css";
import "@shopify/polaris/build/esm/styles.css";

const PolarisProvider = dynamic(() => import("@/service/PolarisProvider"), {
  ssr: false,
  // loading: () => <p>Loading...</p>,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div>
          <PolarisProvider>{children}</PolarisProvider>
        </div>
      </body>
    </html>
  );
}
